name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Build Release APK
        env:
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS}}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEYSTORE: ${{ secrets.KEYSTORE }}
        run: |
          export KEYSTORE_FILE="$RUNNER_TEMP/release.keystore"
          echo "$KEYSTORE" | base64 -di > "$KEYSTORE_FILE"

          ./gradlew assembleDebug

      - name: Store generated APK file
        uses: actions/upload-artifact@v3
        with:
          name: termux-styling
          path: ./app/build/outputs/apk/debug/app-debug.apk
